# Generated by Django 3.2.16 on 2024-05-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'default_related_name': 'amounts', 'verbose_name': 'Ингредиенты в рецептах', 'verbose_name_plural': 'Количество ингредиентов в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='recipesisfavorited',
            options={'default_related_name': 'in_favorited', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Рецепты в избранном'},
        ),
        migrations.AlterModelOptions(
            name='recipesisinshoppingcart',
            options={'default_related_name': 'in_shopping_cart', 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Рецепты в списках покупок'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
